"""add_codigo_barras_to_productos

Revision ID: 266345497597
Revises: 66c7672582ea
Create Date: 2026-05-20 22:35:41.866362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266345497597'
down_revision: Union[str, None] = '66c7672582ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('codigo_barras', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_productos_codigo_barras'), 'productos', ['codigo_barras'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_codigo_barras'), table_name='productos')
    op.drop_column('productos', 'codigo_barras')
    # ### end Alembic commands ###
