"""Fix calculo efectivo caja y pool pre ping

Revision ID: f7d8b6028846
Revises: 9f716576caba
Create Date: 2026-08-23 18:08:50.675530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d8b6028846'
down_revision: Union[str, None] = '9f716576caba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
